[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.2.4"
  # Variáveis de ambiente para build (configure no Netlify Dashboard)
  # VITE_SUPABASE_URL = "https://seu-projeto.supabase.co"
  # VITE_SUPABASE_ANON_KEY = "sua_chave_aqui"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para melhorar performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 